on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --lib --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: test
          args: --lib 

